[cicd] add helm unittest #753

diff --git a/.github/workflows/helm_chart.yml b/.github/workflows/helm_chart.yml
--- a/.github/workflows/helm_chart.yml
+++ b/.github/workflows/helm_chart.yml
@@ -11,6 +11,9 @@ permissions:
   attestations: write
   id-token: write
 
+env:
+  HELM_PATH: ./helm
+
 jobs:
   pre-build:
     runs-on: self-hosted
@@ -27,19 +30,46 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
       
-      - name: Helm template
+      - name: Install Helm unittest plugin (if not exists)
         run: |
-          HELM_PATH="./helm"
+          if ! helm plugin list | grep -q unittest; then
+            helm plugin install https://github.com/helm-unittest/helm-unittest
+          else
+            echo "Helm unittest plugin is already installed, skipping installation."
+          fi
+      
+      - name: Run Helm unittest
+        run: |
+          # Iterate through all directories in HELM_PATH
           for dirpath in "${HELM_PATH}"/* ; do
             [ ! -d "${dirpath}" ] && continue
             HELM_CHART_NAME=$(basename "${dirpath}")
-            echo "Processing directory: ${HELM_CHART_NAME}"
+            echo "Processing chart: ${HELM_CHART_NAME}"
             echo "----------------------------------------"
+            
+            echo "Building dependencies for ${HELM_CHART_NAME}"
             helm dependency build "${HELM_PATH}/${HELM_CHART_NAME}"
+            
+            echo "Linting ${HELM_CHART_NAME}"
             helm lint "${HELM_PATH}/${HELM_CHART_NAME}"
-            helm template soperator "${HELM_PATH}/${HELM_CHART_NAME}"  --namespace soperator
+            
+            echo "Templating ${HELM_CHART_NAME}"
+            helm template soperator "${HELM_PATH}/${HELM_CHART_NAME}" --namespace soperator
+            
+            echo "Running unit tests for ${HELM_CHART_NAME}"
+            if [ -d "${HELM_PATH}/${HELM_CHART_NAME}/tests" ]; then
+              helm unittest "${HELM_PATH}/${HELM_CHART_NAME}"
+              if [ $? -ne 0 ]; then
+                echo "Unit tests failed for chart: ${HELM_CHART_NAME}"
+                exit 1
+              fi
+            else
+              echo "No tests found for ${HELM_CHART_NAME}, skipping unit tests"
+            fi
+            
             echo "----------------------------------------"
           done
+
 
       - uses: engineerd/setup-kind@v0.6.2
         name: Setup kind
